logging:
  level:
    root: WARN
    org.springframework.integration: WARN
spring:
  main:
    banner-mode: "off"
ftp:
  host: localhost
  port: 21
  username: ${user.name}
  password: ${user.password}